### REQUIRED SETTINGS ###

# Set a plain language title for the site.
title: USGov Health Information Rights Complaint Form

# Write a short description for the site. This is used for "meta description."
description: File a complaint for violations of health information privacy and access rights

# Enable for live hosting on GitHub Pages.
# It should start with a slash (/) and then match the name of your repository exactly.
baseurl: /uswds-screener-prototyping-tool

# =============================================================================

### CONTENT SETTINGS ###

# Change the image on the homepage.
# - You can use an absolute link to an existing image.
# - Or you can upload an image to the repository and use a relative link, starting with "../img/"
# - Make sure your filename doesn't have any spaces.
homepage-image: "../img/national-cancer-institute-L8tWZT4CcVQ-unsplash.jpg"

# Define content collections
collections:
  resources:
    output: true

# =============================================================================

### OPTIONAL SETTINGS ###

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Remove generation of additional style.css
theme: null